// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: CachedSongList.proto

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "CachedSongList.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace Arcusical {
namespace LocalMusicStore {

namespace {

const ::google::protobuf::Descriptor* CachedSongList_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  CachedSongList_reflection_ = NULL;

}  // namespace


void protobuf_AssignDesc_CachedSongList_2eproto() {
  protobuf_AddDesc_CachedSongList_2eproto();
  const ::google::protobuf::FileDescriptor* file =
    ::google::protobuf::DescriptorPool::generated_pool()->FindFileByName(
      "CachedSongList.proto");
  GOOGLE_CHECK(file != NULL);
  CachedSongList_descriptor_ = file->message_type(0);
  static const int CachedSongList_offsets_[1] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(CachedSongList, songs_),
  };
  CachedSongList_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      CachedSongList_descriptor_,
      CachedSongList::default_instance_,
      CachedSongList_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(CachedSongList, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(CachedSongList, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      ::google::protobuf::MessageFactory::generated_factory(),
      sizeof(CachedSongList));
}

namespace {

GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_AssignDescriptors_once_);
inline void protobuf_AssignDescriptorsOnce() {
  ::google::protobuf::GoogleOnceInit(&protobuf_AssignDescriptors_once_,
                 &protobuf_AssignDesc_CachedSongList_2eproto);
}

void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    CachedSongList_descriptor_, &CachedSongList::default_instance());
}

}  // namespace

void protobuf_ShutdownFile_CachedSongList_2eproto() {
  delete CachedSongList::default_instance_;
  delete CachedSongList_reflection_;
}

void protobuf_AddDesc_CachedSongList_2eproto() {
  static bool already_here = false;
  if (already_here) return;
  already_here = true;
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::Arcusical::LocalMusicStore::protobuf_AddDesc_CachedSong_2eproto();
  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
    "\n\024CachedSongList.proto\022\031Arcusical.LocalM"
    "usicStore\032\020CachedSong.proto\"F\n\016CachedSon"
    "gList\0224\n\005songs\030\001 \003(\0132%.Arcusical.LocalMu"
    "sicStore.CachedSong", 139);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "CachedSongList.proto", &protobuf_RegisterTypes);
  CachedSongList::default_instance_ = new CachedSongList();
  CachedSongList::default_instance_->InitAsDefaultInstance();
  ::google::protobuf::internal::OnShutdown(&protobuf_ShutdownFile_CachedSongList_2eproto);
}

// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer_CachedSongList_2eproto {
  StaticDescriptorInitializer_CachedSongList_2eproto() {
    protobuf_AddDesc_CachedSongList_2eproto();
  }
} static_descriptor_initializer_CachedSongList_2eproto_;

// ===================================================================

#ifndef _MSC_VER
const int CachedSongList::kSongsFieldNumber;
#endif  // !_MSC_VER

CachedSongList::CachedSongList()
  : ::google::protobuf::Message() {
  SharedCtor();
}

void CachedSongList::InitAsDefaultInstance() {
}

CachedSongList::CachedSongList(const CachedSongList& from)
  : ::google::protobuf::Message() {
  SharedCtor();
  MergeFrom(from);
}

void CachedSongList::SharedCtor() {
  _cached_size_ = 0;
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

CachedSongList::~CachedSongList() {
  SharedDtor();
}

void CachedSongList::SharedDtor() {
  if (this != default_instance_) {
  }
}

void CachedSongList::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* CachedSongList::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return CachedSongList_descriptor_;
}

const CachedSongList& CachedSongList::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_CachedSongList_2eproto();
  return *default_instance_;
}

CachedSongList* CachedSongList::default_instance_ = NULL;

CachedSongList* CachedSongList::New() const {
  return new CachedSongList;
}

void CachedSongList::Clear() {
  songs_.Clear();
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  mutable_unknown_fields()->Clear();
}

bool CachedSongList::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) return false
  ::google::protobuf::uint32 tag;
  while ((tag = input->ReadTag()) != 0) {
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // repeated .Arcusical.LocalMusicStore.CachedSong songs = 1;
      case 1: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED) {
         parse_songs:
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
                input, add_songs()));
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(10)) goto parse_songs;
        if (input->ExpectAtEnd()) return true;
        break;
      }

      default: {
      handle_uninterpreted:
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          return true;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
  return true;
#undef DO_
}

void CachedSongList::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // repeated .Arcusical.LocalMusicStore.CachedSong songs = 1;
  for (int i = 0; i < this->songs_size(); i++) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      1, this->songs(i), output);
  }

  if (!unknown_fields().empty()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
}

::google::protobuf::uint8* CachedSongList::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // repeated .Arcusical.LocalMusicStore.CachedSong songs = 1;
  for (int i = 0; i < this->songs_size(); i++) {
    target = ::google::protobuf::internal::WireFormatLite::
      WriteMessageNoVirtualToArray(
        1, this->songs(i), target);
  }

  if (!unknown_fields().empty()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  return target;
}

int CachedSongList::ByteSize() const {
  int total_size = 0;

  // repeated .Arcusical.LocalMusicStore.CachedSong songs = 1;
  total_size += 1 * this->songs_size();
  for (int i = 0; i < this->songs_size(); i++) {
    total_size +=
      ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
        this->songs(i));
  }

  if (!unknown_fields().empty()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void CachedSongList::MergeFrom(const ::google::protobuf::Message& from) {
  GOOGLE_CHECK_NE(&from, this);
  const CachedSongList* source =
    ::google::protobuf::internal::dynamic_cast_if_available<const CachedSongList*>(
      &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void CachedSongList::MergeFrom(const CachedSongList& from) {
  GOOGLE_CHECK_NE(&from, this);
  songs_.MergeFrom(from.songs_);
  mutable_unknown_fields()->MergeFrom(from.unknown_fields());
}

void CachedSongList::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void CachedSongList::CopyFrom(const CachedSongList& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool CachedSongList::IsInitialized() const {

  for (int i = 0; i < songs_size(); i++) {
    if (!this->songs(i).IsInitialized()) return false;
  }
  return true;
}

void CachedSongList::Swap(CachedSongList* other) {
  if (other != this) {
    songs_.Swap(&other->songs_);
    std::swap(_has_bits_[0], other->_has_bits_[0]);
    _unknown_fields_.Swap(&other->_unknown_fields_);
    std::swap(_cached_size_, other->_cached_size_);
  }
}

::google::protobuf::Metadata CachedSongList::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = CachedSongList_descriptor_;
  metadata.reflection = CachedSongList_reflection_;
  return metadata;
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace LocalMusicStore
}  // namespace Arcusical

// @@protoc_insertion_point(global_scope)
