// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: CachedAlbumList.proto

#ifndef PROTOBUF_CachedAlbumList_2eproto__INCLUDED
#define PROTOBUF_CachedAlbumList_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2006000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2006000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/unknown_field_set.h>
#include "CachedAlbum.pb.h"
// @@protoc_insertion_point(includes)

namespace Arcusical {
namespace LocalMusicStore {

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_CachedAlbumList_2eproto();
void protobuf_AssignDesc_CachedAlbumList_2eproto();
void protobuf_ShutdownFile_CachedAlbumList_2eproto();

class CachedAlbumList;

// ===================================================================

class CachedAlbumList : public ::google::protobuf::Message {
 public:
  CachedAlbumList();
  virtual ~CachedAlbumList();

  CachedAlbumList(const CachedAlbumList& from);

  inline CachedAlbumList& operator=(const CachedAlbumList& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const CachedAlbumList& default_instance();

  void Swap(CachedAlbumList* other);

  // implements Message ----------------------------------------------

  CachedAlbumList* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const CachedAlbumList& from);
  void MergeFrom(const CachedAlbumList& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated .Arcusical.LocalMusicStore.CachedAlbum albums = 1;
  inline int albums_size() const;
  inline void clear_albums();
  static const int kAlbumsFieldNumber = 1;
  inline const ::Arcusical::LocalMusicStore::CachedAlbum& albums(int index) const;
  inline ::Arcusical::LocalMusicStore::CachedAlbum* mutable_albums(int index);
  inline ::Arcusical::LocalMusicStore::CachedAlbum* add_albums();
  inline const ::google::protobuf::RepeatedPtrField< ::Arcusical::LocalMusicStore::CachedAlbum >&
      albums() const;
  inline ::google::protobuf::RepeatedPtrField< ::Arcusical::LocalMusicStore::CachedAlbum >*
      mutable_albums();

  // @@protoc_insertion_point(class_scope:Arcusical.LocalMusicStore.CachedAlbumList)
 private:

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::google::protobuf::RepeatedPtrField< ::Arcusical::LocalMusicStore::CachedAlbum > albums_;
  friend void  protobuf_AddDesc_CachedAlbumList_2eproto();
  friend void protobuf_AssignDesc_CachedAlbumList_2eproto();
  friend void protobuf_ShutdownFile_CachedAlbumList_2eproto();

  void InitAsDefaultInstance();
  static CachedAlbumList* default_instance_;
};
// ===================================================================


// ===================================================================

// CachedAlbumList

// repeated .Arcusical.LocalMusicStore.CachedAlbum albums = 1;
inline int CachedAlbumList::albums_size() const {
  return albums_.size();
}
inline void CachedAlbumList::clear_albums() {
  albums_.Clear();
}
inline const ::Arcusical::LocalMusicStore::CachedAlbum& CachedAlbumList::albums(int index) const {
  // @@protoc_insertion_point(field_get:Arcusical.LocalMusicStore.CachedAlbumList.albums)
  return albums_.Get(index);
}
inline ::Arcusical::LocalMusicStore::CachedAlbum* CachedAlbumList::mutable_albums(int index) {
  // @@protoc_insertion_point(field_mutable:Arcusical.LocalMusicStore.CachedAlbumList.albums)
  return albums_.Mutable(index);
}
inline ::Arcusical::LocalMusicStore::CachedAlbum* CachedAlbumList::add_albums() {
  // @@protoc_insertion_point(field_add:Arcusical.LocalMusicStore.CachedAlbumList.albums)
  return albums_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::Arcusical::LocalMusicStore::CachedAlbum >&
CachedAlbumList::albums() const {
  // @@protoc_insertion_point(field_list:Arcusical.LocalMusicStore.CachedAlbumList.albums)
  return albums_;
}
inline ::google::protobuf::RepeatedPtrField< ::Arcusical::LocalMusicStore::CachedAlbum >*
CachedAlbumList::mutable_albums() {
  // @@protoc_insertion_point(field_mutable_list:Arcusical.LocalMusicStore.CachedAlbumList.albums)
  return &albums_;
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace LocalMusicStore
}  // namespace Arcusical

#ifndef SWIG
namespace google {
namespace protobuf {


}  // namespace google
}  // namespace protobuf
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_CachedAlbumList_2eproto__INCLUDED
