// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: GUID.proto

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "GUID.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace Arcusical {
namespace LocalMusicStore {

namespace {

const ::google::protobuf::Descriptor* GUID_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  GUID_reflection_ = NULL;

}  // namespace


void protobuf_AssignDesc_GUID_2eproto() {
  protobuf_AddDesc_GUID_2eproto();
  const ::google::protobuf::FileDescriptor* file =
    ::google::protobuf::DescriptorPool::generated_pool()->FindFileByName(
      "GUID.proto");
  GOOGLE_CHECK(file != NULL);
  GUID_descriptor_ = file->message_type(0);
  static const int GUID_offsets_[1] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(GUID, rawdata_),
  };
  GUID_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      GUID_descriptor_,
      GUID::default_instance_,
      GUID_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(GUID, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(GUID, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      ::google::protobuf::MessageFactory::generated_factory(),
      sizeof(GUID));
}

namespace {

GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_AssignDescriptors_once_);
inline void protobuf_AssignDescriptorsOnce() {
  ::google::protobuf::GoogleOnceInit(&protobuf_AssignDescriptors_once_,
                 &protobuf_AssignDesc_GUID_2eproto);
}

void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    GUID_descriptor_, &GUID::default_instance());
}

}  // namespace

void protobuf_ShutdownFile_GUID_2eproto() {
  delete GUID::default_instance_;
  delete GUID_reflection_;
}

void protobuf_AddDesc_GUID_2eproto() {
  static bool already_here = false;
  if (already_here) return;
  already_here = true;
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
    "\n\nGUID.proto\022\031Arcusical.LocalMusicStore\""
    "\027\n\004GUID\022\017\n\007rawData\030\001 \002(\014", 64);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "GUID.proto", &protobuf_RegisterTypes);
  GUID::default_instance_ = new GUID();
  GUID::default_instance_->InitAsDefaultInstance();
  ::google::protobuf::internal::OnShutdown(&protobuf_ShutdownFile_GUID_2eproto);
}

// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer_GUID_2eproto {
  StaticDescriptorInitializer_GUID_2eproto() {
    protobuf_AddDesc_GUID_2eproto();
  }
} static_descriptor_initializer_GUID_2eproto_;

// ===================================================================

#ifndef _MSC_VER
const int GUID::kRawDataFieldNumber;
#endif  // !_MSC_VER

GUID::GUID()
  : ::google::protobuf::Message() {
  SharedCtor();
}

void GUID::InitAsDefaultInstance() {
}

GUID::GUID(const GUID& from)
  : ::google::protobuf::Message() {
  SharedCtor();
  MergeFrom(from);
}

void GUID::SharedCtor() {
  _cached_size_ = 0;
  rawdata_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

GUID::~GUID() {
  SharedDtor();
}

void GUID::SharedDtor() {
  if (rawdata_ != &::google::protobuf::internal::kEmptyString) {
    delete rawdata_;
  }
  if (this != default_instance_) {
  }
}

void GUID::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* GUID::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return GUID_descriptor_;
}

const GUID& GUID::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_GUID_2eproto();
  return *default_instance_;
}

GUID* GUID::default_instance_ = NULL;

GUID* GUID::New() const {
  return new GUID;
}

void GUID::Clear() {
  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (has_rawdata()) {
      if (rawdata_ != &::google::protobuf::internal::kEmptyString) {
        rawdata_->clear();
      }
    }
  }
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  mutable_unknown_fields()->Clear();
}

bool GUID::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) return false
  ::google::protobuf::uint32 tag;
  while ((tag = input->ReadTag()) != 0) {
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // required bytes rawData = 1;
      case 1: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadBytes(
                input, this->mutable_rawdata()));
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectAtEnd()) return true;
        break;
      }

      default: {
      handle_uninterpreted:
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          return true;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
  return true;
#undef DO_
}

void GUID::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // required bytes rawData = 1;
  if (has_rawdata()) {
    ::google::protobuf::internal::WireFormatLite::WriteBytes(
      1, this->rawdata(), output);
  }

  if (!unknown_fields().empty()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
}

::google::protobuf::uint8* GUID::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // required bytes rawData = 1;
  if (has_rawdata()) {
    target =
      ::google::protobuf::internal::WireFormatLite::WriteBytesToArray(
        1, this->rawdata(), target);
  }

  if (!unknown_fields().empty()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  return target;
}

int GUID::ByteSize() const {
  int total_size = 0;

  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    // required bytes rawData = 1;
    if (has_rawdata()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::BytesSize(
          this->rawdata());
    }

  }
  if (!unknown_fields().empty()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void GUID::MergeFrom(const ::google::protobuf::Message& from) {
  GOOGLE_CHECK_NE(&from, this);
  const GUID* source =
    ::google::protobuf::internal::dynamic_cast_if_available<const GUID*>(
      &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void GUID::MergeFrom(const GUID& from) {
  GOOGLE_CHECK_NE(&from, this);
  if (from._has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (from.has_rawdata()) {
      set_rawdata(from.rawdata());
    }
  }
  mutable_unknown_fields()->MergeFrom(from.unknown_fields());
}

void GUID::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void GUID::CopyFrom(const GUID& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool GUID::IsInitialized() const {
  if ((_has_bits_[0] & 0x00000001) != 0x00000001) return false;

  return true;
}

void GUID::Swap(GUID* other) {
  if (other != this) {
    std::swap(rawdata_, other->rawdata_);
    std::swap(_has_bits_[0], other->_has_bits_[0]);
    _unknown_fields_.Swap(&other->_unknown_fields_);
    std::swap(_cached_size_, other->_cached_size_);
  }
}

::google::protobuf::Metadata GUID::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = GUID_descriptor_;
  metadata.reflection = GUID_reflection_;
  return metadata;
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace LocalMusicStore
}  // namespace Arcusical

// @@protoc_insertion_point(global_scope)
