

//------------------------------------------------------------------------------
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//------------------------------------------------------------------------------
#include "pch.h"
#include "Controls\SongPlayer.xaml.h"




void ::Arcusical::SongPlayer::InitializeComponent()
{
    if (_contentLoaded)
        return;

    _contentLoaded = true;

    // Call LoadComponent on ms-appx:///Controls/SongPlayer.xaml
    ::Windows::UI::Xaml::Application::LoadComponent(this, ref new ::Windows::Foundation::Uri(L"ms-appx:///Controls/SongPlayer.xaml"), ::Windows::UI::Xaml::Controls::Primitives::ComponentResourceLocation::Application);

    // Get the MediaElement named 'v_mediaElement'
    v_mediaElement = safe_cast<::Windows::UI::Xaml::Controls::MediaElement^>(static_cast<Windows::UI::Xaml::IFrameworkElement^>(this)->FindName(L"v_mediaElement"));
}

void ::Arcusical::SongPlayer::Connect(int connectionId, Platform::Object^ target)
{
    (void)connectionId; // Unused parameter
    (void)target; // Unused parameter
    _contentLoaded = true;
}

