

//------------------------------------------------------------------------------
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//------------------------------------------------------------------------------
#include "pch.h"
#include "Controls\SongPlayer.xaml.h"




void ::Arcusical::SongPlayer::InitializeComponent()
{
    if (_contentLoaded)
        return;

    _contentLoaded = true;

    // Call LoadComponent on ms-appx:///Controls/SongPlayer.xaml
    ::Windows::UI::Xaml::Application::LoadComponent(this, ref new ::Windows::Foundation::Uri(L"ms-appx:///Controls/SongPlayer.xaml"), ::Windows::UI::Xaml::Controls::Primitives::ComponentResourceLocation::Application);

}

void ::Arcusical::SongPlayer::Connect(int connectionId, Platform::Object^ target)
{
    switch (connectionId)
    {
    case 1:
        (safe_cast<::Windows::UI::Xaml::Controls::Primitives::ButtonBase^>(target))->Click +=
            ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::Arcusical::SongPlayer::*)(Platform::Object^, Windows::UI::Xaml::RoutedEventArgs^))&SongPlayer::PlayPauseButton_Clicked);
        break;
    }
    (void)connectionId; // Unused parameter
    (void)target; // Unused parameter
    _contentLoaded = true;
}

