

//------------------------------------------------------------------------------
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//------------------------------------------------------------------------------
#include "pch.h"
#include "Pages\MainPage.xaml.h"
#include "Controls\SongListControl.xaml.h"
#include "Controls\AlbumListControl.xaml.h"




void ::Arcusical::MainPage::InitializeComponent()
{
    if (_contentLoaded)
        return;

    _contentLoaded = true;

    // Call LoadComponent on ms-appx:///Pages/MainPage.xaml
    ::Windows::UI::Xaml::Application::LoadComponent(this, ref new ::Windows::Foundation::Uri(L"ms-appx:///Pages/MainPage.xaml"), ::Windows::UI::Xaml::Controls::Primitives::ComponentResourceLocation::Application);

    // Get the SongListControl named 'v_songListControl'
    v_songListControl = safe_cast<::Arcusical::SongListControl^>(static_cast<Windows::UI::Xaml::IFrameworkElement^>(this)->FindName(L"v_songListControl"));
    // Get the AlbumListControl named 'v_albumListControl'
    v_albumListControl = safe_cast<::Arcusical::AlbumListControl^>(static_cast<Windows::UI::Xaml::IFrameworkElement^>(this)->FindName(L"v_albumListControl"));
}

void ::Arcusical::MainPage::Connect(int connectionId, Platform::Object^ target)
{
    (void)connectionId; // Unused parameter
    (void)target; // Unused parameter
    _contentLoaded = true;
}

